POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkVtaWxpYSIsImlkIjoiNjM0YWY3OTgyZTc0NTU3NzUwNzkzMjAwIiwiaWF0IjoxNjY1OTQ2NjM1fQ.1Oo4Xfk6iTQB8fyzTwLsnbbacwVmA1NuJ7OAkWnXIQQ

{
    "author": "oke",
    "url": "www.oke.mauno",
    "likes": 420
}